# Generated by Django 4.2.7 on 2025-11-16 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        verbose_name="Tipo Sanguíneo",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Altura (cm)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nome do Contato de Emergência",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Telefone do Contato de Emergência",
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(
                        blank=True,
                        help_text="Informações médicas gerais do paciente",
                        verbose_name="Observações Médicas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome da Vacina"),
                ),
                (
                    "dose",
                    models.CharField(
                        help_text="Ex: 1ª dose, 2ª dose, dose única, reforço",
                        max_length=50,
                        verbose_name="Dose",
                    ),
                ),
                (
                    "application_date",
                    models.DateField(verbose_name="Data de Aplicação"),
                ),
                (
                    "next_dose_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Próxima Dose"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número do Lote"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fabricante"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Unidade de saúde onde foi aplicada",
                        max_length=200,
                        verbose_name="Local de Aplicação",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccines",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacina",
                "verbose_name_plural": "Vacinas",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nome do Medicamento"
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text="Ex: 500mg, 10ml",
                        max_length=100,
                        verbose_name="Dosagem",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="Ex: 2x ao dia, de 8 em 8 horas",
                        max_length=100,
                        verbose_name="Frequência",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data de Início")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Término"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("is_active", models.BooleanField(default=True, verbose_name="Em Uso")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "prescribed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescribed_medications",
                        to="accounts.doctorprofile",
                        verbose_name="Prescrito por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
                "ordering": ["-is_active", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergen",
                    models.CharField(
                        help_text="Substância que causa alergia",
                        max_length=200,
                        verbose_name="Alérgeno",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Leve"),
                            ("moderate", "Moderada"),
                            ("severe", "Grave"),
                        ],
                        default="mild",
                        max_length=20,
                        verbose_name="Gravidade",
                    ),
                ),
                (
                    "reaction",
                    models.TextField(
                        blank=True,
                        help_text="Descrição da reação alérgica",
                        verbose_name="Reação",
                    ),
                ),
                (
                    "diagnosed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Diagnóstico"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alergia",
                "verbose_name_plural": "Alergias",
                "ordering": ["-severity", "allergen"],
            },
        ),
    ]
