# Generated by Django 4.2.7 on 2026-01-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical_records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="chief_complaint",
            field=models.TextField(
                blank=True,
                help_text="Motivo da consulta relatado pelo paciente",
                verbose_name="Queixa Principal",
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="diagnosis",
            field=models.TextField(blank=True, verbose_name="Diagnóstico"),
        ),
    ]
