# Generated by Django 4.2.7 on 2025-11-19 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view_patient", "Visualização de Paciente"),
                            ("view_record", "Visualização de Prontuário"),
                            ("create_record", "Criação de Prontuário"),
                            ("update_record", "Atualização de Prontuário"),
                            ("generate_pdf", "Geração de PDF (Receita/Exame)"),
                        ],
                        max_length=50,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="Detalhes")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Acesso",
                "verbose_name_plural": "Logs de Acesso",
                "ordering": ["-timestamp"],
            },
        ),
    ]
