# Generated by Django 4.2.7 on 2025-11-16 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("appointments", "Relatório de Consultas"),
                            ("patients", "Relatório de Pacientes"),
                            ("doctors", "Relatório de Médicos"),
                            ("prescriptions", "Relatório de Prescrições"),
                            ("exams", "Relatório de Exames"),
                            ("vaccines", "Relatório de Vacinas"),
                            ("custom", "Relatório Personalizado"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Relatório",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Inicial"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Data Final"),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filtros aplicados ao relatório em formato JSON",
                        verbose_name="Filtros",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        default="pdf",
                        max_length=10,
                        verbose_name="Formato",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="reports/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gerado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório",
                "verbose_name_plural": "Relatórios",
                "ordering": ["-created_at"],
            },
        ),
    ]
