# Generated by Django 4.2.7 on 2025-11-16 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="Data da Consulta")),
                (
                    "scheduled_time",
                    models.TimeField(verbose_name="Horário da Consulta"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=30, verbose_name="Duração (minutos)"),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("first_visit", "Primeira Consulta"),
                            ("return", "Retorno"),
                            ("emergency", "Emergência"),
                            ("routine", "Rotina"),
                        ],
                        default="first_visit",
                        max_length=20,
                        verbose_name="Tipo de Consulta",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("confirmed", "Confirmada"),
                            ("in_progress", "Em Andamento"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                            ("no_show", "Não Compareceu"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Motivo da Consulta"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelado em"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Motivo do Cancelamento"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.doctorprofile",
                        verbose_name="Médico",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "ordering": ["-scheduled_date", "-scheduled_time"],
                "unique_together": {("doctor", "scheduled_date", "scheduled_time")},
            },
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("scheduled", "Agendado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="accounts.doctorprofile",
                        verbose_name="Médico",
                    ),
                ),
                (
                    "new_appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_request",
                        to="appointments.appointment",
                        verbose_name="Novo Agendamento",
                    ),
                ),
                (
                    "original_appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="appointments.appointment",
                        verbose_name="Consulta Original",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Retorno",
                "verbose_name_plural": "Solicitações de Retorno",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reminder", "Lembrete"),
                            ("cancellation", "Cancelamento"),
                            ("rescheduling", "Remarcação"),
                            ("doctor_absence", "Ausência do Médico"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Notificação",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensagem")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lida")),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="appointments.appointment",
                        verbose_name="Agendamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação de Agendamento",
                "verbose_name_plural": "Notificações de Agendamentos",
                "ordering": ["-sent_at"],
            },
        ),
    ]
