# Generated by Django 4.2.7 on 2025-11-16 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        help_text="Motivo da consulta relatado pelo paciente",
                        verbose_name="Queixa Principal",
                    ),
                ),
                ("symptoms", models.TextField(blank=True, verbose_name="Sintomas")),
                (
                    "physical_examination",
                    models.TextField(blank=True, verbose_name="Exame Físico"),
                ),
                ("diagnosis", models.TextField(verbose_name="Diagnóstico")),
                (
                    "treatment_plan",
                    models.TextField(blank=True, verbose_name="Plano de Tratamento"),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o prontuário foi fechado (não pode mais ser editado)",
                        verbose_name="Fechado",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fechado em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record",
                        to="appointments.appointment",
                        verbose_name="Consulta",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="accounts.doctorprofile",
                        verbose_name="Médico",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prontuário Médico",
                "verbose_name_plural": "Prontuários Médicos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medications",
                    models.TextField(
                        help_text="Lista de medicamentos prescritos",
                        verbose_name="Medicamentos",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Instruções"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="Válida até"),
                ),
                (
                    "prescription_file",
                    models.FileField(
                        blank=True,
                        help_text="Receita em formato PDF",
                        upload_to="prescriptions/%Y/%m/",
                        verbose_name="Arquivo da Receita",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="accounts.doctorprofile",
                        verbose_name="Médico",
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="medical_records.medicalrecord",
                        verbose_name="Prontuário",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita Médica",
                "verbose_name_plural": "Receitas Médicas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Criado"),
                            ("updated", "Atualizado"),
                            ("closed", "Fechado"),
                            ("comment_added", "Comentário Adicionado"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="medical_records.medicalrecord",
                        verbose_name="Prontuário",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Prontuário",
                "verbose_name_plural": "Históricos de Prontuários",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecordComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Comentário")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="medical_records.medicalrecord",
                        verbose_name="Prontuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário de Prontuário",
                "verbose_name_plural": "Comentários de Prontuários",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("blood", "Exame de Sangue"),
                            ("urine", "Exame de Urina"),
                            ("imaging", "Exame de Imagem"),
                            ("biopsy", "Biópsia"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Exame",
                    ),
                ),
                (
                    "exam_name",
                    models.CharField(max_length=200, verbose_name="Nome do Exame"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Solicitado"),
                            ("scheduled", "Agendado"),
                            ("completed", "Realizado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="requested",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "requested_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data da Solicitação"
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Agendada"
                    ),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Realização"
                    ),
                ),
                ("result", models.TextField(blank=True, verbose_name="Resultado")),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        upload_to="exams/%Y/%m/",
                        verbose_name="Arquivo do Resultado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_exams",
                        to="accounts.doctorprofile",
                        verbose_name="Médico Solicitante",
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="medical_records.medicalrecord",
                        verbose_name="Prontuário",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exame",
                "verbose_name_plural": "Exames",
                "ordering": ["-requested_date"],
            },
        ),
    ]
